# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/calderwoodra/google-style-precommit-hook.git
    sha: 58870133c601e5f8677513b2a527c9948d98899b
    hooks:
      - id: google-style-java